### PR TITLE
Fixes cache in CachalotPanel, Version 1.4.2

### PR DESCRIPTION
**Pull request by eriktelepovsky**
Fixes cache issue in CachalotPanel described in the gitter.im lobby.

### CODE REVIEW

**Comment by BertrandBordage** [comment]
Looks good to me, but avoid making a release in the same commit as something else, please.
I’ll merge this and publish the new version in a few days.

**Comment by eriktelepovsky** [comment]
All right. I will know in the future.

**Comment by BertrandBordage** [comment]
I merge this, but I’ll partially revert it, there will not be a version 1.4.2.

**Comment by eriktelepovsky** [comment]
Thank you.

**Pull request merged**
