### PR TITLE
Functionality to disable django-cachalot during a thread

### PR DESCRIPTION
**Pull request by jayden-emergence**
With 2 additional tests to help with coverage.

### CODE REVIEW

**Comment by jayden-emergence** [comment]
I don't think there is a way that we can have coverage because of six not having a way to import get_ident from one source.

**Comment by jayden-emergence** [comment]
If the import was switched to being a try except and if the coverage stuff would count the line that blows up as being run, it could then be possible to get 100%.  But I don't know how the coverage code figures out which lines have run or not.

**Comment by jayden-emergence** [comment]
Everything looks like it should have worked but these 2 jobs failed at:

* https://travis-ci.org/BertrandBordage/django-cachalot/jobs/295420012
* https://travis-ci.org/BertrandBordage/django-cachalot/jobs/295419986

```The command "mysql -u root -e 'CREATE DATABASE cachalot;'" failed and exited with 1 during .```

**Comment by schuyler1d** [comment]
This looks like an awesome feature!  One use case, I don't see represented is wanting to 'force refresh' the cache -- i.e. the results should come from the database, but then they should update the existing cache records.  I think that would be doable if at least one path checked DISABLE_CACHING   in [_get_result_or_execute_query](https://github.com/BertrandBordage/django-cachalot/pull/88/files#diff-40c59379c971668149d0966ab0918e66R153) but let the rest of the setting proceed.

**Comment by BertrandBordage** [comment]
Closing following this comment: https://github.com/BertrandBordage/django-cachalot/issues/83#issuecomment-386762699.

**Pull request closed without merging**
