### PR TITLE
Allow using DummyCache together with Cachalot

### PR DESCRIPTION
**Pull request by JockeTF**
Allowing DummyCache can be useful for testing.

### CODE REVIEW

**Comment by sorlandet** [comment]
Please, add also django_elasticache.memcached.ElastiCache to VALID_CACHE_BACKENDS

**Comment by BertrandBordage** [comment]
@JockeTF: I’m not 100% sure if that’s good to add it. Because of course, there is no problem if you use django-cachalot with DummyCache, no query will be cached, and that’s all, no possible problem. But I’m afraid some newbies will think that cachalot works with DummyCache, and they’ll complain that their website is still slow, etc. I already got 2 private reports from users that configured a memcached connection without actually having memcached installed and running…
So I merge this change and it’ll be in version 1.2.0, but if 2 or more people send reports about that, I’ll remove it.

@sorlandet: No, since it’s not supported and will never be. Use [`SILENCED_SYSTEM_CHECKS`](https://docs.djangoproject.com/en/1.9/ref/settings/#silenced-system-checks) if you want to use it anyway, at your own risks.

**Comment by JockeTF** [comment]
Makes sense, thanks!

**Comment by sorlandet** [comment]
```django_elasticache``` uses ```PyLibMCCache``` which is in ```VALID_CACHE_BACKENDS```
so "will never be" looks little bit strange from your side:-)
looks like its better to check subclass of a valid classes (using ```issubclass``` assertion) in that case even commonly used ```django_elasticache``` backend can pass check without ```SILENCED_SYSTEM_CHECKS```

**Comment by BertrandBordage** [comment]
@sorlandet I stand by what I said, django-elasticache will never be supported since it connects to a proprietary service which therefore:
- can’t be tested (unless someone pays an access for django-cachalot for the years to come)
- is not open source, so we don’t know how it works and when & how its behaviour changes

**Comment by sorlandet** [comment]
@BertrandBordage okay, i think i'll continue using PyLibMCCache backend as you think that django-elasticache is untested and relay on aws (not open source). thank you.

**Pull request merged**
